### ISSUE TITLE
Step 7 Part 2

### ISSUE THREAD

**Issue by samihoda** [StdCarrot/iamovpn#2]
Now that docopt is installed, I get this error:

![image](https://user-images.githubusercontent.com/172117/73492023-b3c45300-4364-11ea-9195-0d0ef8f99a24.png)

**Comment by StdCarrot** [comment]
This project only support Python3.5+.
But you used Python2.7 in your screenshot.
Please retry after install Python3.5+(I recommend 3.7 or 3.8)

**Comment by samihoda** [comment]
I used the same commands in the instructions. Not sure why it installed an older version. trying now

**Comment by samihoda** [comment]
I ran the command for requirements again, and it said everything was installed. I made sure I have python3.7 now. This is what it shows now
![image](https://user-images.githubusercontent.com/172117/73508392-a755ef80-4390-11ea-9afb-2aac955386af.png)

**Comment by StdCarrot** [comment]
That's odd.
Let me know Linux version and pip version(by command: pip3 -V )
And did you use virtualenv?

**Comment by samihoda** [comment]
Did not use virtualenv, above command shows (on Ubuntu 18.04)
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

**Comment by samihoda** [comment]
I started running random --reinstall commands for things like python3-apt, python3-docopt, etc
now the error is no module named 'netifaces', however I know it is already installed...

**Comment by StdCarrot** [comment]
Your pip running on python3.6.
Make sure use Python3.7 pip using pip3.7 install blah

**Comment by samihoda** [comment]
It says pip3.7: command not found, but pip3 install blah works...

**Comment by StdCarrot** [comment]
Maybe you install only python3.7 interpreter.
You have two options.
First, use system default puthon3=python3.6
Or, install python3.7 pip using get-pip.py

**Comment by samihoda** [comment]
I tried get-pip.py, looks like this site https://github.com/pypa/pip/issues/5599 says to use virtualenv instead when this issue happens. Will try that.

**Comment by samihoda** [comment]
It finally installed. Starting openvpn though returns an error, and will not start. Sigh

**Comment by StdCarrot** [comment]
This is not a bug, it is about python installation.
Please make sure python version and pip version are same.

**Comment by StdCarrot** [comment]
@samihoda Can you open new issue to that with full logs of openvpn and iamovpn?
